
version: '2.0'

services:
    app:
        build: .
        restart: always
        volumes:
            - "~/Pictures:/media/pictures:ro"
            - "~/Videos:/media/videos:ro"
            - "~/Music:/media/music:ro"
            - "./config:/home/gerbera/.config/gerbera"
        network_mode: "host"
        restart: always
