
version: '2.4'

services:
    app:
        build: 
          context: .
          args:
              VERSION: 1.4.0

        restart: always
        volumes:
            - "/media/pi/pny/mega/Pictures:/media/pictures:ro"
            - "/media/pi/pny/mega/Music:/media/music:ro"
            - "./config:/home/gerbera/.config/gerbera"
        network_mode: "host"
        restart: always
