
version: '2.0'

services:
    app:
        build: .
        restart: always
        volumes:
            - "/media/pi/pny/mega/Pictures:/media/pictures:ro"
            - "/media/pi/pny/mega/Music:/media/music:ro"
            - "./config:/home/gerbera/.config/gerbera"
        network_mode: "host"
        restart: always
