
version: '2.0'

services:
    app:
        build: 
          context: .
          args:
            VERSION: 1.4.0
        restart: always
        volumes:
            - "~/Pictures:/media/pictures:ro"
            - "~/Videos:/media/videos:ro"
            - "~/Music:/media/music:ro"
            - "${PWD}/config:/home/gerbera/.config/gerbera"
        network_mode: "host"
        restart: always
