#!/bin/bash
VERSION=$(curl -sL https://api.github.com/repos/gerbera/gerbera/releases/latest | awk '/"tag_name": "v(.*)",/ {split($2, xout, /"/); print xout[2]}' | sed s/^v//)
docker build -t $DOCKER_REPO:$VERSION -t $DOCKER_REPO . --build-arg VERSION=$VERSION
