name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build . --build-arg=VERSION="1.3.5" --file Dockerfile --tag gerbera:1.3.5
            
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: gerbera
        tag: 1.3.5
        username: gpbenton
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
