name: Docker Image CI

on: [push]
env:
  VERSION: 1.3.5

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run:  |
        docker build . --build-arg=VERSION=$VERSION --file Dockerfile --tag docker.pkg.github.com/gpbenton/gerbera/gerbera:$VERSION
        docker login docker.pkg.github.com -u gpbenton -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/gpbenton/gerbera/gerbera:$VERSION
        docker tag docker.pkg.github.com/gpbenton/gerbera/gerbera:$VERSION docker.pkg.github.com/gpbenton/gerbera/gerbera:latest
        docker push docker.pkg.github.com/gpbenton/gerbera/gerbera:latest
        docker logout docker.pkg.github.com
