name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build . --build-arg=VERSION="1.3.5" --file Dockerfile --tag docker.pkg.github.com/gpbenton/gerbera:1.3.5
    - name: login to docker
      run:  docker login docker.pkg.github.com -u gpbenton -p ${ secrets.GITHUB_TOKEN }
    - name: push to github
      run:  docker push docker.pkg.github.com/gpbenton/gerbera:1.3.5
    - name: logout from docker
      run:  docker logout docker.pkg.github.com
            
