name: Check for New Release

on:
  schedule:
    - cron:  '0 1 * * sat'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check if latest release in my docker hub repository
      run: |
        VERSION=$(curl -sL https://api.github.com/repos/gerbera/gerbera/releases/latest | jq -r ".tag_name" )
        wget -q https://registry.hub.docker.com/v1/repositories/gpbenton/gerbera/tags -O - | grep --invert-match --silent $VERSION

    - uses: actions/checkout@v1
    - name: Call a POST url to start the build on the docker hub
      run: |
        wget --post-data "" https://hub.docker.com/api/build/v1/source/af6fa0c8-3949-4a4e-86c2-be8dbb9da5bc/trigger/8cc327c9-538e-48fc-8dd4-47c3961da199/call/
